spring:
  datasource:
    url: jdbc:mysql://localhost:3306/file
    username: root
    password: 1234
  application:
    name: FILE-SERVICE

  jpa:
    hibernate:
      ddl-auto: none
    #    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB